### PR TITLE
Master > Main update

### PR DESCRIPTION
**Pull request by jpvajda**

### CODE REVIEW

**Comment by jpvajda** [comment]
There seemed to be PRs linger on the master branch.. 🤔

**Comment by jpvajda** [comment]
I'm not clear on why we still have a master branch and main in this repo. @jbeveland27 any ideas?

**Comment by jbeveland27** [comment]
@jpvajda It's likely that when the default branch was updated from `master` to `main`, there were open PRs that were never reassigned to the new main branch. There's no reason to keep `master` around as far as I know.

**Comment by jbeveland27** [comment]
Snyk might need to be updated to point to the right default branch too

**Comment by jpvajda** [comment]
@jbeveland27 Thanks for the info! If I can get your 👍  on this I can approve the merge.

**Comment by jpvajda** [comment]
as a closing task on this, I'll delete the master branch once we get it all caught up.

**Review by jbeveland27 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
